---
title: "Reproducible Research"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

```{r}
#| label: setup
#| echo: false
```


## Foundational Principles of Data Management {.smaller}

1. **F**indability
2. **A**ccessibility
3. **I**nteroperability
4. **R**eusability (Reproducibility)

\bigskip If we care about long term data useability, sharing and stewardship, then we need to think about how and when to make our data FAIR. This is especially important if we want our work to be accessed by multiple stakeholders (i.e., industry, public, education, policy, *computers?*)

\bigskip These ideas will come in handy when writing future "data management plans" required for many grants.


## What is reproducible research?

> "By reproducible, I mean that your work can be repeated by other researchers and they can arrive at the same results. For this to be the case, your work must be well documented, and your methods, code, and data all need to be available so that other researchers have the materials to reproduce everything." -VS Buffalo


## Reproducible vs. replicable research

1. *Reproducible* - Given only 1) the raw data and 2) the scripts (i.e., code), one can produce the same set of results and figures. Not almost the same set, the **SAME SET**.
1. *Replicable* - Can one repeat the same experiment and reach the same conclusion?

In this class, when we discuss reproducible research, this is what we will mean. Outside of this course, these terms are often used more generally or interchangeably. 


## Problems you are trying to avoid

1. How did I make this figure?
1. Why did I eliminate those data points?
1. Where are the data I eliminated?
1. What analysis did I use to reach this conclusion?
1. I just added new samples. It is going to be so much work to run the analyses again!


## Basic principles

1. Everything via scripts
1. Everything automated with documentation (e.g., comments)
1. Raw data is read only
1. All output reproducible


## Point and click vs. scripting analyses


## Insulating data from analysis {.smaller}

Raw data should always be read-only. Treat raw data like an endangered species.

- /Project
    - /RawData
    - /Data
    - /Scripts
    - /Plots

- Store your data in its rawest form
    - Excel ok
- Do any calculations/analysis elsewhere
    - **No stats or plots in Excel**
    - So many reasons


## Basic tools for reproducible research

1. R
1. Markdown
1. Version control
    - OK = sequential numbers (never call a file "final")
    - Better = Git (See Git & Github resources)


## Why R for reproducible research?

- Free, now and forever
- Comprehensive and flexible (perhaps too much so for beginners)
- Portable code (Windows, OS X, Unix-like)
- Publication quality plotting
- Encourages good data analysis practices
    - No point and click


## R will become essential for scientists (you, your students)

- As important as Word and Excel
- Learn it now while you have time and energy


## Why not ...

- Probably won't have careers as biostatisticians (SAS, Stata)
- Won't tie to you non-free software (SAS, SPSS, Systat, Stata, NCSS/PASS, MATLAB)
- Huge data (>$10^8$ observations) is rarely an issue (SAS, Stata, python, julia)
- Speed is rarely an issue for us (C/C++, julia, MATLAB)
- Python (NumPy/SciPy/pandas/statsmodel) is less mature as a general statistical programming language
- R is open source


## R will make you angry

- Unforgiving
- Opaque
- Often inscrutable errors
    - Learning to deal with errors is critical to reproducibility


## R will make you happy

- Keeps a record of what you did for you
- (Almost) anything is possible in R
- Beautiful, publication-ready, reproducible plots


## R $\neq$ RStudio

- RStudio is an interface to R
- R can be run without RStudio.
    - The reverse is not true.
- RStudio is one of the most important things to ever happen to R
- These slides were written in R (RStudio and Quarto)


## R Markdown (`Rmd`) / Quarto (`qmd`)

- Text-based markup language (i.e., HTML)
- Variant of markdown
- Render to different formats (PDF, HTML, Word)
- Inline R code
    - Your text and analysis coexist together in one file
- Resources
    - Markdown information
    - Guides and Tutorials
    

## Reproducibility is an investment for your future self

Going "the hard way" now is the easy way in the long run.

Be kind to your future self.

> Your closest collaborator is you six months ago, but you don't reply to emails.

