---
title: "Course Mechanics"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

```{r}
#| label: setup
#| echo: false


```


## About us


## About you

- Your preferred name
- Your pronouns
- Your home department and home lab
- Your research area


## What you need

- Laptop (fully charged)
- Can do attitude
- Patience
- Presence


## Why is this class is structured this way

- We have taught it in the traditional way, and it does not work as well.
    - Working together is key
- Yes it is more effort on your part to coordinate, etc.
    - Teaching is how you know you have learned something


## Book, etc.

There is no one-size-fits-all statistics textbook.

- Any that we chose would be a compromise.
- Lots of free material online.
- Many recommendations on Canvas if you are looking for a book.


## Online lectures

- Available Fridays
- Watch, pause, take notes, re-watch, look up topics you don't understand, etc.


## Grading

Participation: Your participation grade in the course will be a function of:

- Quiz questions (completion)
- Discussion board (completion)
- Problem sets (completion)
- Peer evaluations (both your own completion of and others' evaluations of you)
- In class contributions

Don't worry about what numbers are in the gradebook.


## Grading

Progress Checks:

- Each 4 week block will end with a Progress Check.
    - No new material that week
    - Class time used to answer questions
    - Like a problem set
- You may not work with other members of the class or anyone else on this assignment
- You should use all other available resources (books, notes, lectures, internet, etc.).


## Quiz questions

- In between most of the lectures
    - e.g., Watch a lecture, answer some questions
- Not graded, but you *do* need to complete them.
    - Thoughtful reflection about any you get incorrect


## Problem sets

- Practical experience
- Gradually less guidance
- Experience solving challenges as a team
- All members of the group should participate
- Each group member should submit the same set of answers


## Groups


## Working together

- Many possible successful strategies
    - Remember you have access to lecture code, the google, etc.
- One unsuccessful strategy
    - Splitting up the problem set & not learning all the parts
    - You should only leave class early if your entire group has turned in the problem set


## Peer evaluations


## Reviewing your work

- Problem sets not graded
- You are responsible for checking your group's answers against the answer key
    - Learn from reading other code
    - Many ways to the same outcome


## Typical weekly schedule {.smaller}

**Friday**: Lectures, "quizzes", readings (when applicable) posted online to Canvas

**Tuesday** at midnight: 

- Previous week's problem set submitted through Canvas
- Peer evaluations

**Thursday** at midnight: 

- Watch lectures
- Weekly quizzes
- Discussion board (note problem set key is available)

**Friday**: Class meeting, discuss any issues from that week (anonymous or not), work together on next problem set.


## Missing class

- Let us know as far in advance as possible
- Work alone or we will create virtual groups


## How do I find help?

- Your group members
- Lecture slides
- Us
- Resources on Canvas
- Links we provide throughout course
- Internet (but use thoughtfully)


## Asking questions

- Each week you will ask a question about what topics were the most challenging to you.
- Start from what you know. Think about what you do not understand.
- Try to be as specific as possible

"I understand that ... I am trying to understand ..."


## Artificial intelligence is not intelligence

- We (unfortunately) use human terms to describe LLMs: "intelligence", "learn", "understand", "think", "know", "hallucinate"
- LLMs generate responses based on probabilities (what character/word comes next?), which are derived from their training data.
- [Large Language Models explained briefly (YouTube)](https://www.youtube.com/watch?v=LPZh9BOjkQs)


## Predicting based on probability

Predict $y$ if $x = 3$.

$$y = 2x + 3$$


## What are the next two numbers in the sequence?

$$1, 3, 5, 7$$
or

$$1, 3, 5, 7, 17, 19, 21$$

LLMs can answer the first but not the second.


## Ways in which large language models can fail you {.smaller}

- *Outdated and/or incorrect information*: LLMs are trained on historical data, which might have changed or be incorrect
- *Inability to explain*: If you don't code it yourself, you will have greater challenges explaining it
- *Debugging challenges*: If your code doesn't work, then figuring out why will be more challenging
- *Short circuit* the development of problem-solving skills in our learn-by-doing approach
    - Be willing to fail and keep trying.
- *Limiting you creativity and innovation*: There are many ways to solve a coding challenge


## Course AI guidelines: "AI Integration Allowed: Human-in-the-Loop"

- Generative AI may be used in this course. The content you submit is your responsibility. Be sure your work accurately reflects your understanding and avoids these pitfalls.
- You are responsible for understanding what you submit. Simply copying an AI-generated solution does not contribute to gaining understanding.


## Course AI guidelines: "AI Integration Allowed: Human-in-the-Loop"

If you use AI, please put this statement at the top of your problem set/progress check:

> "I acknowledge the use of AI in completing this assignment and would like to provide a brief explanation of how I utilized AI, specifically [LLM], as a tool to support my work. For this assignment, I employed [LLM] to [describe the specific purpose or task]. To do so I crafted the following prompts: [List prompts used]"


## Before you ask AI, ask yourself ...

... how will this help me learn?


## This Week's questions


## Coming soon

- Extracting from data frames and matrices
- Data visualization
- Importing data
- Cleaning data
- Functions

Asking these questions helps us know how much time you want to spend on these topics


## tibble vs. data.frame

> Tibble is an upgraded version of data.frames. But  in what cases can you only use data.frames, not tibble and vice versa?

- There are rare cases where it matters.
- We will encounter a few and point them out.
- Don't worry about it.


## Learning R functions and Productivity

> What is the best way to write and understand detailed codes, especially when there are too many functions/assignments in the code? What would be the best way to practice?

> How have you found it easiest to learn/memorize functions in R? Do you recommend practice, notes, flashcards, etc?

> What things should I consider to improve productivity in R studio?


## Why would one make slides in R vs. Powerpoint, etc.?

