---
title: "Unit 8 In Class Discussion"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

```{r}
#| label: setup
#| message: false
#| warning: false

library(tidyverse)
library(cowplot)

theme_set(theme_cowplot())

```


## Next week

- Quiz due **Wednesday**
- Review (start working on) Progress Check 2 before class


## Problem set 7

- Why is it not a good idea to combine the data from the two trout studies? Is it because the number of dead fish is smaller than the number of surviving fish? Why does that hinder the ability to combine the data from the two studies, if the studies were designed to be replicates of one another?


## Where do coefficients come from?

> I did not understand why and how to calculate the coefficient from residuals for each predictors (such as fat coefficient or lactose coefficient from the lecture example) before calculating the multiple regression. What if there are more than 2 predictors for the outcome variable? 



## Quiz 8.3

- For the summary tables could we go over what exactly they are telling us?
- What does `Intercept` represent
- What specifically (other than correlation values) should we be looking for in `ggscatmat()` plots? When should we not proceed?
- Practice today with PS 8
    - Review next week


## Thinking about multicollinearity

- How would you interpret coefficients of predictors when there's a high degree of shared variance among them?


## Questions deferred to next Friday

- Masking
- Mixed models (and Units 9 and 12)
- Planned comparisons


