---
title: "Advanced Topics"
subtitle: "Introduction"
author:
  - Elizabeth King
  - Kevin Middleton
format:
  revealjs:
    theme: [default, custom.scss]
    standalone: true
    self-contained: true
    logo: QMLS_Logo.png
    slide-number: true
    show-slide-number: all
code-annotations: hover
bibliography: QMLS_Bibliography.bib
csl: evolution.csl
---

## Topics we have covered

- Programming with data, reproducible research
- Data wrangling and visualization
- Probability and likelihood
- Lots of linear models, some multilevel
- Making decisions, making errors in decisions
- Model comparison
- Experimental design


## Techniques for using what you have learned

- Start simple
- Recognize problems you have seen before
- Adapt code for your own use
    - View this course as a set of recipes


## Non-exhaustive list of topics we have not covered in depth

- Randomization and simulation
- Multivariate approaches
- Non-linear models
- Bayesian inference
- Multilevel models
- Non-Gaussian outcome variables


## Where to go from here

- Quantitative Methods in Life Sciences 2 (BIO_SC 8642)
    - 5 week modules on focused topics
- Other formal or informal classes (MU, online)
- Study groups (pick a book and work through)
- Discussion groups (Dataphiles, R-MUsers slack)
- Self-study


## Skills for self-study you have already learned

- Comfort with what you don't know & confidence you can grow and learn
- Patience with incremental growth and skill building
- Acceptance that multiple exposures are needed for growth & learning
- Break down unfamiliar problems into smaller questions & steps


## Tips for approaching self-study & becoming a modern life scientist

- Curiosity about how things work "under the hood"
- Channel toddler energy
    - ask why...a lot
- Use the literature
- Try, fail, try again
    - Run examples, simulate data, etc.
    - Believe in yourself

